version: "3.5"

services:
  app:
    build:
      context: apache
    ports:
      - "80:80"
    volumes:
      - "./app:/app"

  mysql8-db:
    image: "mysql:8.0.19"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_DATABASE=smartstore"
      - "MYSQL_USER=smartstore"
      - "MYSQL_PASSWORD=smartstore"
      - "MYSQL_ROOT_PASSWORD=smartstore"
    ports:
      - "3306:3306"
    volumes:
      - "mysql8-data:/var/lib/mysql"

volumes:
  mysql8-data:
